spring:
  output:
    ansi:
      enabled: detect
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  #  所有po都要放在此package下
  type-aliases-package: cn.wuxiangknow.single.po
  configuration:
    map-underscore-to-camel-case: true
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
